### ISSUE TITLE
Django cannot reach Postgres

### ISSUE THREAD

**Issue by szarnyasg** [gangefors/aws-mailman3#10]
I'm trying to set up mailman using Docker Compose. I experimented with various setups from the [`docker-mailman`](https://github.com/maxking/docker-mailman) repository but none on them worked (MySQL didn't start, PostgreSQL/SQLite got  stuck on https://github.com/maxking/docker-mailman/issues/443). Therefore, I switched to this repository but ran into the same issue - when trying to request a password reset, Django cannot connect to Postgres using the psycopg2 library:

```
$ sudo cat ~/opt/mailman/web/logs/uwsgi-error.log
[...]
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
psycopg2.OperationalError: server closed the connection unexpectedly
	This probably means the server terminated abnormally
	before or while processing the request.
[...]
```

I tried connecting to the database container from the web container using the `psql` tool and it worked fine:

```bash
$ docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' aws-mailman3_database_1 
172.19.199.2

$ docker exec -it aws-mailman3_mailman-web_1 /bin/bash

bash-5.0# apk add postgresql-client
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.12/community/x86_64/APKINDEX.tar.gz
OK: 117 MiB in 82 packages

bash-5.0# psql -h 172.19.199.2 -U mailman mailmandb
psql (12.6, server 9.6.22)
Type "help" for help.

mailmandb=#
```

I turned on the logging for Postgres:
```
$ sudo vim ~/opt/mailman/database/postgresql.conf

# set the following
logging_collector = on
log_directory = 'pg_log'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'

$ docker-compose down && docker-compose up
```

However, there are no log entries generated by the website, indicating that the Django requests do not reach the database. (If I connect through `psql`, the errors are logged.)
```
$ docker exec -it aws-mailman3_database_1 /bin/bash

bash-5.1# cat /var/lib/postgresql/data/pg_log/postgresql-2021-05-17_112444.log 
LOG:  database system was shut down at 2021-05-17 11:24:41 UTC
LOG:  MultiXact member wraparound protections are now enabled
LOG:  autovacuum launcher started
LOG:  database system is ready to accept connections
```

Are you aware of a workaround for this issue? Is there any way to extract more information from on what fails for Django's connection attempt?

**Comment by gangefors** [comment]
I've not seen this issue when setting up my instance of Mailman3.

And the limited logs you provided doesn't help much since it just shows that a db query failed.
If you can provide the complete logs for all services (web, core, db, etc) it might help debugging this problem.

I would guess that the db connection is not the root issue since the site actually starts and gives you the option to actually request a password reset mail. It wouldn't be able to do this if the DB connection never worked, it must set up tables on first startup and that part seems to work.

**Comment by szarnyasg** [comment]
Thanks for the prompt answer. I increased the logging level by adding
```
DEBUG = True
```
to `/opt/mailman/web/settings_local.py`. Now I can see a clear error message in Django which shows that the actual error is `SMTPServerDisconnected` so it's not an issue with Postgres.

For the record, based on the [mailman documentation](https://docs.mailman3.org/_/downloads/en/latest/pdf/#page=27), I also added the following entries to `mailman-extra.cfg`:

```
[logging.bounce]
level: DEBUG
path: bounce.log

[logging.database]
level: DEBUG
path: database.log

[logging.debug]
level: DEBUG
path: debug.log

[logging.error]
level: DEBUG
path: error.log

[logging.http]
level: DEBUG
path: http.log

[logging.runner]
level: DEBUG
path: runner.log

[logging.smtp]
level: DEBUG
path: smtp.log
```

```
# copy file, cleanup logs, start
sudo cp mailman-extra.cfg ~/opt/mailman/core/
sudo rm -rf ~/opt/mailman/core/var/logs/ && sudo mkdir ~/opt/mailman/core/var/logs/
docker-compose up
```

These logs did not contain any information regarding the issue, so the problem is somewhere between Django and the SMTP server. I'll keep investigating.
